# Generated from `nettrace -h`
# Regenerate by running a small script against the current binary

complete -c nettrace -s s -l saddr -d "filter source ip/ipv6 address"
complete -c nettrace -s d -l daddr -d "filter dest ip/ipv6 address"
complete -c nettrace -l addr -d "filter source or dest ip/ipv6 address"
complete -c nettrace -s S -l sport -d "filter source TCP/UDP port"
complete -c nettrace -s D -l dport -d "filter dest TCP/UDP port"
complete -c nettrace -s P -l port -d "filter source or dest TCP/UDP port"
complete -c nettrace -s p -l proto -d "filter L3/L4 protocol, such as 'tcp', 'arp'"
complete -c nettrace -l netns -d "filter by net namespace inode"
complete -c nettrace -l netns-current -d "filter by current net namespace"
complete -c nettrace -l pid -d "filter by current process id(pid)"
complete -c nettrace -l min-latency -d "filter by the minial time to live of the skb in us"
complete -c nettrace -l pkt-len -d "filter by the IP packet length (include header) in byte"
complete -c nettrace -l tcp-flags -d "filter by TCP flags, such as: SAPR"
complete -c nettrace -l basic -d "use 'basic' trace mode, don't trace skb's life"
complete -c nettrace -l diag -d "enable 'diagnose' mode"
complete -c nettrace -l diag-quiet -d "only print abnormal packet"
complete -c nettrace -l diag-keep -d "don't quit when abnormal packet found"
complete -c nettrace -l drop -d "skb drop monitor mode, for replace of 'droptrace'"
complete -c nettrace -l drop-stack -d "print the kernel function call stack of kfree_skb"
complete -c nettrace -l sock -d "enable 'sock' mode"
complete -c nettrace -l rtt -d "enable 'rtt' in statistics mode"
complete -c nettrace -l rtt-detail -d "enable 'rtt' in detail mode"
complete -c nettrace -l filter-srtt -d "filter by the minial first-acked rtt in ms"
complete -c nettrace -l filter-minrtt -d "filter by the minial last-acked rtt in ms"
complete -c nettrace -l latency-show -d "show latency between kernel functions"
complete -c nettrace -l latency-free -d "account the latency of skb free"
complete -c nettrace -l latency -d "enable 'latency' mode"
complete -c nettrace -s t -l trace -d "enable trace group or trace. Some traces are disabled by default, use \"all\" to enable all"
complete -c nettrace -l force -d "skip some check and force load nettrace"
complete -c nettrace -l ret -d "show function return value"
complete -c nettrace -l detail -d "show extern packet info, such as pid, ifname, etc"
complete -c nettrace -l date -d "print timestamp in date-time format"
complete -c nettrace -s c -l count -d "exit after receiving count packets"
complete -c nettrace -l hooks -d "print netfilter hooks if dropping by netfilter"
complete -c nettrace -l tiny-show -d "set this option to show less infomation"
complete -c nettrace -l trace-stack -d "print call stack for traces or group"
complete -c nettrace -l trace-matcher -d "traces that can match packet(default all)"
complete -c nettrace -l trace-exclude -d "traces that should be disabled"
complete -c nettrace -l trace-noclone -d "don't trace skb clone"
complete -c nettrace -l trace-free -d "custom the free functions"
complete -c nettrace -l func-stats -d "only do the statistics for function call"
complete -c nettrace -l rate-limit -d "limit the output to N/s, not valid in diag/default mode"
complete -c nettrace -l btf-path -d "custom the path of BTF info of vmlinux"
complete -c nettrace -s v -d "show log information"
complete -c nettrace -l debug -d "show debug information"
complete -c nettrace -s h -l help -d "show help information"
complete -c nettrace -s V -l version -d "show nettrace version"
